Ossp master update for gramine, logstash, threatplaybook, struts
Be-Secure/BeSLighthouse pull request #358
Opened 2023-02-27 04:36 UTC by sand-hya

2023-02-28 06:26 UTC, sudhirverma requested changes

2023-02-28 06:26 UTC, sudhirverma commented on bes_theme/assets/data/OSSP-master.js
> +		{
@sand-hya JSON format is not correct you need to provide comma after each object

2023-02-28 06:26 UTC, sudhirverma commented on bes_theme/assets/data/OSSP-master.js
> +		{
same here as above comment

2023-02-28 06:26 UTC, sudhirverma commented on bes_theme/assets/data/OSSP-master.js
> +		{
same here as above comment

2023-02-28 06:26 UTC, sudhirverma commented on bes_theme/assets/data/OSSP-master.js
> +		{
same here as first comment

2023-02-28 06:27 UTC, sudhirverma commented
Please tag the issue in description section

2023-03-01 04:39 UTC, asa1997 commented
@sand-hya Please address the comments.

2023-03-01 08:02 UTC, asa1997 approved these changes
@sand-hya LGTM

2023-03-01 08:02 UTC, merged