#89 Opstrace Added the project details in OSSP-master
Be-Secure/BeSLighthouse pull request #424
Opened 2023-03-10 14:34 UTC by Aditi8007

2023-03-14 04:18 UTC, asa1997 requested changes
@Aditi8007 Please add the version details file as well. Also, please resolve the conflicts.

2023-03-14 08:30 UTC, asa1997 commented on bes_theme/assets/data/OSSP-master.js
> +			"issue_url": "https://github.com/Be-Secure/BeSLighthouse/issues/89",
Url should point to Be-Secure repo not BeSLighthouse repo.

2023-03-14 08:31 UTC, asa1997 requested changes
@Aditi8007 Please address the comment and resolve the conflicts.

2023-03-15 10:22 UTC, asa1997 approved these changes
@Aditi8007 @harimohanr LGTM.
@Aditi8007 Please do update the scores too asap.

2023-03-17 04:50 UTC, asa1997 requested changes
@Aditi8007 Please resolve the conflicts

2023-03-17 06:44 UTC, sudhirverma reviewed
@Aditi8007 can you move this Pull Request to besecure-osspoi-datastore

2023-03-20 09:43 UTC, asa1997 commented
Closing this pr as it is outdated.

2023-03-20 09:43 UTC, closed without merging