osspmaster and versiondetails updated
Be-Secure/BeSLighthouse pull request #427
Opened 2023-03-14 13:23 UTC by Vidyaaa24

[#91](https://github.com/Be-Secure/Be-Secure/issues/91)
[#92](https://github.com/Be-Secure/Be-Secure/issues/92)
[#95](https://github.com/Be-Secure/Be-Secure/issues/95)
[#237](https://github.com/Be-Secure/Be-Secure/issues/237)
[#238](https://github.com/Be-Secure/Be-Secure/issues/238)
[#240](https://github.com/Be-Secure/Be-Secure/issues/240)

2023-03-15 07:23 UTC, asa1997 requested changes
@Aditi8007 
- The file name format for the version details file is incorrect. Please make the appropriate changes.
- The id for flink is shown as 91 in PoI table. Please correct that as well.

2023-03-15 12:06 UTC, sudhirverma requested changes

2023-03-15 12:06 UTC, sudhirverma commented on bes_theme/assets/data/OSSP-master.js
>        name: "Swagger-Codegen",
can you check the name `Swagger-Codegen` is different in versiondetails file

2023-03-17 06:42 UTC, sudhirverma reviewed
@Vidyaaa24 Can we class this Pull Request if you move this PR in besecure-osspoi-datastore

2023-03-17 06:49 UTC, closed without merging