added sbom visualization code
Be-Secure/BeSLighthouse pull request #437
Opened 2023-03-21 06:24 UTC by pramit-d

added code to assessment_report.js & version_summary.js
https://github.com/Be-Secure/BeSLighthouse/issues/433

2023-03-21 11:20 UTC, asa1997 commented on bes_theme/assets/javascripts/assessment_reports.js
> +  else if (report == "sbom") { // sbom dir
@pramit-d This check is not required.

2023-03-21 11:20 UTC, asa1997 commented on bes_theme/assets/javascripts/version_summary.js
> +  else if(id == "sbom"){
@pramit-d This check is not required.

2023-03-22 05:40 UTC, pramit-d commented
> @pramit-d Please address the comments.

updated

2023-03-23 06:33 UTC, asa1997 approved these changes
@pramit-d @harimohanr LGTM

2023-03-23 06:33 UTC, asa1997 commented
@harimohanr 
![image](https://user-images.githubusercontent.com/58501088/227122452-cdd0fd0a-112b-4247-8d09-4816004ba5e3.png)

2023-03-23 06:35 UTC, asa1997 commented on bes_theme/assets/javascripts/assessment_reports.js
> +  table += "<tr><th>Package name</th><th>version</th><th>supplier</th><th>downloadLocation</th><th>license</th></tr>"
- version -> Version
- supplier -> Supplier
- downloadLocation -> Download Location
- license -> License

2023-03-23 06:35 UTC, asa1997 commented on bes_theme/assets/javascripts/assessment_reports.js
> +  table += "<tr><th>Package name</th><th>version</th><th>supplier</th><th>downloadLocation</th><th>license</th></tr>"
@pramit-d Please do make these changes as well.

2023-03-23 06:54 UTC, asa1997 approved these changes
@pramit-d LGTM

2023-03-23 06:55 UTC, asa1997 requested changes
@pramit-d Please resolve the conflicts

2023-03-23 06:55 UTC, pramit-d commented
> @pramit-d Please resolve the conflicts

@asa1997 working on that

2023-03-23 07:02 UTC, asa1997 approved these changes
@pramit-d @harimohanr LGTM

2023-03-23 07:02 UTC, merged