Structure change under "all_bes_repos"
Be-Secure/BeSLighthouse pull request #84
Opened 2021-09-24 04:02 UTC by asa1997

@panickervinod 
The structure of the repo details has been changed under "all_bes_repos"

"all_bes_repos": [                                                                  
                {
                    "id": 391939220,
                    "name": "prometheus",
                    "url": "https://github.com/Be-Secure/prometheus"
                }
                
            ]

2021-09-24 06:54 UTC, panickervinod commented on bes_theme/assets/data/OSSP-master.js
> +                "prometheus": "https://github.com/prometheus/prometheus",
this should be same as "all_bes_repos"

2021-09-24 06:58 UTC, panickervinod commented on bes_theme/assets/data/OSSP-master.js
> +            "COM": {
"Community led" , is a valid label

2021-09-27 02:47 UTC, jobyko commented
Correction needed for label
eg. there is direct label available for CNCF projects, COM-F-CNCF

2021-09-27 02:49 UTC, jobyko requested changes
Correction needed for label
eg. there is direct label available for CNCF projects, COM-F-CNCF

2021-10-03 17:39 UTC, merged